parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_DRIVER): ''
    env(DATABASE_HOST): ''
    env(DATABASE_PORT): ''
    env(DATABASE_NAME): ''
    env(DATABASE_USER): ''
    env(DATABASE_URL): ''
    env(DATABASE_PASSWORD): ''

doctrine:
    dbal:
        default_connection: default
        types:
            date: App\DBAL\Types\UTCDateType
        #            time: AppBundle\DBAL\Types\UTCTimeType
        #            datetime: AppBundle\DBAL\Types\UTCDateTimeType
        connections:
            default:
                driver: '%env(resolve:DATABASE_DRIVER)%'
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                dbname: '%env(resolve:DATABASE_NAME)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                charset: UTF8
                server_version: 9.6

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            softdeleteable: true
            blameable: true
            loggable: true
            sluggable: true
