# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    files_adapter:
      local:
        directory: '%kernel.project_dir%/data/files'

    backups_adapter:
      local:
        directory: '%kernel.project_dir%/data/backups'

    images_adapter:
      local:
        directory: '%kernel.project_dir%/data/images'

  filesystems:
    files:
      adapter: files_adapter
      mount: files_filesystem

    backups:
      adapter: backups_adapter
      mount: backups_filesystem

    images:
      adapter: images_adapter
      mount: images_filesystem
