vich_uploader:
    db_driver: orm

    mappings:
        file:
            uri_prefix: /file
            upload_destination: file_filesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        image:
            uri_prefix: /image
            upload_destination: image_filesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer
