vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        file:
            upload_destination: files_filesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        image:
            upload_destination: images_filesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
