vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
        type: attribute
    mappings:
        files:
            uri_prefix: /media
            upload_destination: oneup_flysystem.default_fylesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer