vich_uploader:
    db_driver: orm

    mappings:
        file:
            uri_prefix: /file
            upload_destination: '%kernel.project_dir%/data/files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        image:
            uri_prefix: /image
            upload_destination: '%kernel.project_dir%/data/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
#            directory_namer: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
